backend:
  name: git-gateway
  branch: main

site_url: https://takakitaoyaji.com

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

media_library:
  name: cloudinary
  config:
    cloud_name: duh9jrbpp
    api_key: 624184293779926

locale: "ja"

collections:
  - name: "blog"
    label: "ブログ"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - {
          label: "投稿日",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
        }
      - {
          label: "著者",
          name: "author",
          widget: "string",
          default: "高北おやじ",
        }
      - { label: "キービジュアル", name: "image", widget: "image" }
      - { label: "概要", name: "excerpt", widget: "text" }
      - { label: "本文", name: "body", widget: "markdown" }
